-- Users: usergroup fields
ALTER TABLE users ADD COLUMN group_title TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN group_stars INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN group_color TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN custom_title TEXT NOT NULL DEFAULT '';
-- Users: count fields
ALTER TABLE users ADD COLUMN digest_posts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN ol_time INTEGER NOT NULL DEFAULT 0;
-- Users: profile fields
ALTER TABLE users ADD COLUMN gender INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN birth_year INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN birth_month INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN birth_day INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN reside_province TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN reside_city TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN graduate_school TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN bio TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN interest TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN qq TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN site TEXT NOT NULL DEFAULT '';
-- Users: status fields
ALTER TABLE users ADD COLUMN last_activity INTEGER NOT NULL DEFAULT 0;
-- Threads: type classification
ALTER TABLE threads ADD COLUMN type_name TEXT NOT NULL DEFAULT '';
