#!/usr/bin/env bun
/**
 * build-init-sql — concat apps/worker/migrations/*.sql into a single
 * INIT_SQL string, written to apps/worker/src/test-support/init-sql.generated.ts.
 *
 * Used by L2-fast (bun:test, in-process Worker) to materialize the schema
 * into a fresh bun:sqlite `:memory:` database. L2-http and L3 still apply
 * migrations via `wrangler d1 migrations apply --local --persist-to`.
 *
 * Two modes:
 *   - default          : regenerate the file from migrations (writes to disk).
 *   - --check          : verify the on-disk file is in sync with current
 *                        migrations. Exits 1 if hashes differ. Used by
 *                        scripts/typecheck.sh so PRs that change migrations
 *                        without re-generating fail at typecheck.
 *
 * The generated file is committed to git so clean checkouts (CI uses
 * `bun install --ignore-scripts`) have it without a postinstall step.
 *
 * IMPORTANT: INIT_SQL is intended for fresh `:memory:` databases. It contains
 * `ALTER TABLE … ADD COLUMN` statements that fail on re-run. L2-http / L3
 * use real wrangler migrations and never touch INIT_SQL.
 */

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");
const MIGRATIONS_DIR = join(REPO_ROOT, "apps/worker/migrations");
const OUTPUT_FILE = join(REPO_ROOT, "apps/worker/src/test-support/init-sql.generated.ts");

interface Built {
	sql: string;
	hash: string;
	files: string[];
}

function build(): Built {
	const files = readdirSync(MIGRATIONS_DIR)
		.filter((f) => f.endsWith(".sql"))
		.sort(); // 0000_init_schema.sql, 0023_…, … in numeric order

	const parts: string[] = [];
	for (const file of files) {
		const body = readFileSync(join(MIGRATIONS_DIR, file), "utf8");
		parts.push(`-- ── ${file} ────────────────────────────────────────────`);
		parts.push(body.trimEnd());
		parts.push("");
	}
	const sql = parts.join("\n");
	const hash = createHash("sha256").update(sql).digest("hex");
	return { sql, hash, files };
}

function render({ sql, hash, files }: Built): string {
	// Inline as a template literal; escape backticks/${} so the SQL embeds
	// safely. Migration SQL has neither in practice but be defensive.
	const escaped = sql.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
	return `/* AUTO-GENERATED by scripts/build-init-sql.ts. DO NOT EDIT BY HAND.
 *
 * Regenerate with: bun run prepare:test-sql
 * Verify in sync : bun run prepare:test-sql --check
 *
 * Source migrations (sha256: ${hash}):
${files.map((f) => ` *   - ${f}`).join("\n")}
 *
 * IMPORTANT: This SQL is for fresh \`:memory:\` databases only — it contains
 * ALTER TABLE … ADD COLUMN statements that fail on re-run. L2-http / L3 use
 * real wrangler migrations and never touch INIT_SQL.
 */
export const INIT_SQL = \`${escaped}\`;

export const INIT_SQL_HASH = ${JSON.stringify(hash)};

export const INIT_SQL_SOURCE_FILES = ${JSON.stringify(files, null, "\t")} as const;
`;
}

function readCurrent(): string | null {
	try {
		return readFileSync(OUTPUT_FILE, "utf8");
	} catch {
		return null;
	}
}

function extractHash(content: string): string | null {
	const m = content.match(/export const INIT_SQL_HASH = "([0-9a-f]{64})"/);
	return m ? m[1] : null;
}

function main(): void {
	const isCheck = process.argv.includes("--check");
	const built = build();
	const rendered = render(built);

	if (isCheck) {
		const current = readCurrent();
		if (current === null) {
			console.error(
				`❌ ${OUTPUT_FILE.replace(`${REPO_ROOT}/`, "")} does not exist. Run: bun run prepare:test-sql`,
			);
			process.exit(1);
		}
		const currentHash = extractHash(current);
		if (currentHash !== built.hash) {
			console.error(
				`❌ INIT_SQL is out of sync with migrations.\n` +
					`   on-disk hash : ${currentHash ?? "(missing)"}\n` +
					`   computed hash: ${built.hash}\n` +
					`   Run: bun run prepare:test-sql`,
			);
			process.exit(1);
		}
		// Also ensure the rendered output matches byte-for-byte (catches stale
		// header comments / file list drift even when the SQL hash is the same
		// as some past version that happens to collide).
		if (current !== rendered) {
			console.error(
				`❌ ${OUTPUT_FILE.replace(`${REPO_ROOT}/`, "")} is stale (header / file list drift). Run: bun run prepare:test-sql`,
			);
			process.exit(1);
		}
		console.log(
			`✅ INIT_SQL up to date (${built.files.length} migrations, hash=${built.hash.slice(0, 8)})`,
		);
		return;
	}

	writeFileSync(OUTPUT_FILE, rendered);
	console.log(
		`📝 Wrote ${OUTPUT_FILE.replace(`${REPO_ROOT}/`, "")} (${built.files.length} migrations, hash=${built.hash.slice(0, 8)})`,
	);
}

main();
